
-- DROP TABLE IF EXISTS Client CASCADE ;
-- DROP TABLE IF EXISTS Stats CASCADE;

CREATE TABLE Client (
  id INTEGER PRIMARY KEY ,
  age INTEGER,
  sex SMALLINT
);

CREATE TABLE Stats (
  id SERIAL,
  userId INTEGER REFERENCES Client(id),
  ts TIMESTAMP,
  action SMALLINT
);